// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriWeek.Data;

#nullable disable

namespace NutriWeek.Migrations
{
    [DbContext(typeof(NutriWeekDbContext))]
    [Migration("20260926095725_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriWeek.Data.Models.DailyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeeklyMenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyMenuId");

                    b.ToTable("DailyMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeeklyMenuId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeeklyMenuId = 1
                        });
                });

            modelBuilder.Entity("NutriWeek.Data.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DishType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 520,
                            Description = "A balanced meal with chicken, rice and vegetables.",
                            DishType = 0,
                            Ingredients = "Chicken breast, rice, tomato, cucumber, olive oil",
                            Instructions = "Cook the rice. Cook the chicken. Chop the vegetables and serve everything together.",
                            Name = "Chicken Rice Bowl",
                            Portions = 2,
                            PreparationTime = 30
                        },
                        new
                        {
                            Id = 2,
                            Calories = 430,
                            Description = "Pasta with vegetables and tomato sauce.",
                            DishType = 2,
                            Ingredients = "Pasta, tomato sauce, zucchini, bell pepper, parmesan",
                            Instructions = "Cook the pasta. Cook the vegetables and tomato sauce. Mix everything together.",
                            Name = "Vegetarian Pasta",
                            Portions = 2,
                            PreparationTime = 25
                        },
                        new
                        {
                            Id = 3,
                            Calories = 480,
                            Description = "Baked salmon served with fresh vegetables.",
                            DishType = 1,
                            Ingredients = "Salmon, broccoli, carrots, olive oil, lemon",
                            Instructions = "Season the salmon and vegetables. Bake until cooked and serve with lemon.",
                            Name = "Salmon with Vegetables",
                            Portions = 2,
                            PreparationTime = 35
                        },
                        new
                        {
                            Id = 4,
                            Calories = 350,
                            Description = "Oatmeal with banana and fresh berries.",
                            DishType = 3,
                            Ingredients = "Oats, oat milk, banana, blueberries, strawberries",
                            Instructions = "Cook the oats with oat milk. Add sliced banana and berries before serving.",
                            Name = "Vegan Oatmeal",
                            Portions = 1,
                            PreparationTime = 10
                        });
                });

            modelBuilder.Entity("NutriWeek.Data.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyMenuId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyMenuId");

                    b.HasIndex("DishId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyMenuId = 1,
                            DishId = 4,
                            MealType = 0
                        },
                        new
                        {
                            Id = 2,
                            DailyMenuId = 1,
                            DishId = 1,
                            MealType = 1
                        },
                        new
                        {
                            Id = 3,
                            DailyMenuId = 1,
                            DishId = 3,
                            MealType = 2
                        },
                        new
                        {
                            Id = 4,
                            DailyMenuId = 2,
                            DishId = 4,
                            MealType = 0
                        },
                        new
                        {
                            Id = 5,
                            DailyMenuId = 2,
                            DishId = 2,
                            MealType = 1
                        },
                        new
                        {
                            Id = 6,
                            DailyMenuId = 2,
                            DishId = 1,
                            MealType = 2
                        });
                });

            modelBuilder.Entity("NutriWeek.Data.Models.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WeeklyMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Healthy Week",
                            WeekStartDate = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NutriWeek.Data.Models.DailyMenu", b =>
                {
                    b.HasOne("NutriWeek.Data.Models.WeeklyMenu", "WeeklyMenu")
                        .WithMany("DailyMenus")
                        .HasForeignKey("WeeklyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyMenu");
                });

            modelBuilder.Entity("NutriWeek.Data.Models.Meal", b =>
                {
                    b.HasOne("NutriWeek.Data.Models.DailyMenu", "DailyMenu")
                        .WithMany("Meals")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriWeek.Data.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMenu");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("NutriWeek.Data.Models.DailyMenu", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("NutriWeek.Data.Models.WeeklyMenu", b =>
                {
                    b.Navigation("DailyMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
